print("the + or - indicates whether player level is above or below the agreement level (- for below, + for above).")
calcned = input("please enter your calc need: cc-, cc+, cc=, cb+, cb-, cb=, cb-1")
if calcned == ("cc-"):
	x1 = int(input("Please enter your st loss or gains: "))
	x2 = int(input("please enter your mt loss or gains"))
	x3 = int(input("please enter your lt loss or gains"))
	y = int(input("Please enter the # of levels the agreement is above the player level : "))
	n = int(input("Please enter the number of players in your agreement: "))
	St = (-1*abs(x1*y)+n)
	print('your CC- calculations are:')
	print('short term points are:', St)
	Mt = (-1*abs(x2*y)+n*2)
	print("medium term points are:", Mt)
	Lt = (-1*abs(x3*y)+n*3)
	print("long term points are equal to:", Lt)
elif calcned == ("cc+"):
	x1 = int(input("Please enter your st loss or gains: "))
	x2 = int(input("please enter your mt loss or gains: "))
	x3 = int(input("please enter your lt loss or gains: "))
	y = int(input("Please enter the # of levels the agreement is below the player level : "))
	n = int(input("Please enter the number of players in your agreement: "))
	print('Your CC+ calculations are:')
	St = ((x1-y)+n)
	print('short term points are:', St)
	Mt = ((x2-y)+n*2)
	print("medium term points are:", Mt)
	Lt = ((x3-y)+n*3)
	print("long term points are equal to:", Lt)
elif calcned == ("cc="):
	x1 = int(input("Please enter your st loss or gains: "))
	x2 = int(input("please enter your mt loss or gains"))
	x3 = int(input("please enter your lt loss or gains"))
	n = int(input("Please enter the number of players in your agreement: "))
	print("Your CC= calculations are:")
	St = (x1+n)
	print('short term points are:', St)
	Mt = (x2+(n*2))
	print("medium term points are:", Mt)
	Lt = (x3+(n*3))
	print("long term points are equal to:", Lt)
elif calcned == ("cb-"):
	x1 = int(input("Please enter your st loss or gains: "))
	x2 = int(input("please enter your mt loss or gains"))
	x3 = int(input("please enter your lt loss or gains"))
	y = int(input("Please enter the # of levels the agreement is above the player level : "))
	n = int(input("Please enter the number of players in your agreement: "))
	St = (-1*abs(x1*y)+n)
	print('your CB- calculations are:')
	print('short term points are:', St)
	Mt = (-1*abs(x2*y)+n*2)
	print("medium term points are:", Mt)
	Lt = (-1*abs(x3*y)+n*3)
	print("long term points are equal to:", Lt)

